### ISSUE TITLE
Don't use 10^10^10 for seq example

### ISSUE THREAD

**Issue by googleson78** [triffon/fp-slides#3]
Regarding the slides on laziness:

There is a an example to demonstrate that `seq` only forces it's first argument to WHNF.
The example is something like:
```haskell
h l = l `seq` head l
> h [1..10^10^10]
```
This freezes, confusing the audience into believing that `seq` actually **does evaluate** the entire list.

The issue is that before we even start to generate the list `[1..10^10^10]` we need to first see if `1 > 10^10^10`, meaning we need to evaluate `10^10^10`, which is obviously not going to happen.

It would be better if the example used something like `[1..100000000000000000]` instead.

**Comment by googleson78** [comment]
Alternative solution idea: Use a tuple instead

**Comment by triffon** [comment]
The example in the slides does not use lists, so it's OK, I will make a note not to use lists during the actual lecture.
